### ISSUE TITLE
Fix broken fission dependency bugs

### ISSUE THREAD

**Issue by samuelandert** [omoearth/omo-li#152]

**Comment by samuelandert** [comment]
In generell, the initial and re-authentication still takes at least in Europe, especially in the evening, many times up to 2-3 minutes, sometimes never and there is a connection timeout. 

In addition to that, there are a few screenshots I collected over the last days, with various connection issues, before, during and after first authentication and re-authentication:

<img width="1440" alt="Bildschirmfoto 2020-12-29 um 09 33 14" src="https://user-images.githubusercontent.com/747161/103299028-eb67cf00-49fb-11eb-85f4-72b5154182ed.png">

<img width="1440" alt="Bildschirmfoto 2020-12-29 um 15 37 35" src="https://user-images.githubusercontent.com/747161/103299013-e4d95780-49fb-11eb-9887-3b220d743b62.png">

<img width="1254" alt="Bildschirmfoto 2020-12-29 um 16 33 10" src="https://user-images.githubusercontent.com/747161/103299005-de4ae000-49fb-11eb-837b-7e636e211bc5.png">

<img width="1440" alt="Bildschirmfoto 2020-12-29 um 09 34 34" src="https://user-images.githubusercontent.com/747161/103298988-d723d200-49fb-11eb-9134-5742653f9494.png">

This last one translates as the service worker could not be registered/updated, which sometimes happens, when I create a new fission account. 

<img width="1397" alt="Bildschirmfoto 2020-12-29 um 16 34 18" src="https://user-images.githubusercontent.com/747161/103298963-cbd0a680-49fb-11eb-919d-5be53e377410.png">

**Comment by samuelandert** [comment]
<img width="1440" alt="Bildschirmfoto 2021-01-06 um 10 10 38" src="https://user-images.githubusercontent.com/747161/103750716-7aca3f00-5007-11eb-962c-59ef6fff1878.png">

**Comment by icidasset** [comment]
Just wanted to note that `auth.fission.codes/web_modules/ipfs.min.js:2 Uncaught (in promise) Error: stream ended before 1 bytes became available` isn't an actual error, this is us pinging our IPFS node and canceling the ping. But yeah, we need to hide that 😅 

`(DOMException: The "counter" has an unexpected length -- must be 16 bytes)` should only happen when one of the lobby instances is an older version. You can check the version by looking at the source of the page (or hovering with cursor over the auth tag). But I'll do some testing to be sure. Or wait... this doesn't happen in webnative itself right? Not sure if I'm reading the logs right.

Thanks for nothing the `ports[0]` and websocket errors, I hadn't seen those.
Will get back to you on that and the connection issues.

**Comment by jaensen** [comment]
> Or wait... this doesn't happen in webnative itself right? Not sure if I'm reading the logs right.   

It was triggered from webnative or the keystore. The callstack is unfortunately a bit misleading. 
Seems to be related to https://www.w3.org/TR/WebCryptoAPI/#aes-ctr-operations
```
Encrypt
If the counter member of normalizedAlgorithm does not have length 16 bytes, then throw an OperationError.
```
```
Decrypt
If the counter member of normalizedAlgorithm does not have length 16 bytes, then throw an OperationError.
```

**Comment by samuelandert** [comment]
Found another new error while debugging on iOS:

<img width="1407" alt="Bildschirmfoto 2021-01-06 um 21 36 54" src="https://user-images.githubusercontent.com/747161/103817690-76ce0980-5067-11eb-80d5-e23defdea7cf.png">
<img width="1411" alt="Bildschirmfoto 2021-01-06 um 21 36 27" src="https://user-images.githubusercontent.com/747161/103817692-77ff3680-5067-11eb-9b7a-9f27a09a05ef.png">

**Comment by icidasset** [comment]
That's IPFS being IPFS, it's trying to connect to peers that are closeby (ie. you can see it's trying to connect to a localhost address, but failing). You can ignore those errors. I sadly haven't found a way to silence those errors, but they're working on it.

**Comment by icidasset** [comment]
Scratch the above ☝️ This should now be fixed.
I hope the initial connection setup has improved somewhat now.
`stream ended before 1 bytes became available` error is gone too.

I released webnative v0.21.2 with a few fixes as well, see the changelog for more info:
https://github.com/fission-suite/webnative/blob/master/CHANGELOG.md#v0212

`initialise` will now return a rejected Promise if the browser & context is not supported.
So in Firefox's private mode, this'll be the case.

Are you still seeing the `ports[0] is undefined` error?

---

Still working on the following issues:
- https://github.com/fission-suite/webnative/issues/158
- https://github.com/fission-suite/webnative/issues/164
- https://github.com/fission-suite/webnative/issues/159

Let me know if I missed any.
Thanks!

**Comment by samuelandert** [comment]
Nice work. I can't see the ports[0] error anymore. 
What I still experience is this one, but I think this was related to the uppercase username:
<img width="608" alt="Bildschirmfoto 2021-01-13 um 22 08 44" src="https://user-images.githubusercontent.com/747161/104574304-243bb100-5656-11eb-8981-2cb6b096e59b.png">

And sometimes the web socket-connection error: 
<img width="683" alt="Bildschirmfoto 2021-01-13 um 21 43 19" src="https://user-images.githubusercontent.com/747161/104574428-4c2b1480-5656-11eb-9af4-a905cb8ba49f.png">

And this one, but I don't remember how and when it happened:
<img width="641" alt="Bildschirmfoto 2021-01-13 um 22 17 08" src="https://user-images.githubusercontent.com/747161/104574511-6664f280-5656-11eb-8b74-54a5fdd8c9d7.png">

**Comment by icidasset** [comment]
Hey 👋  We deployed our ipfs cluster yesterday and I think we addressed quite a few issues from this list. How are you finding the stability & performance at the moment?

**Comment by samuelandert** [comment]
At first look looking very good, not perfect but getting there. Will test during the next days and come back, with feedback.
